2019-10-08 14:27:28,553 ERROR: Exception on /login [GET] [in /home/oddmin/Projects/FlaskMegaTutorial/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/oddmin/Projects/FlaskMegaTutorial/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/oddmin/Projects/FlaskMegaTutorial/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/oddmin/Projects/FlaskMegaTutorial/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/oddmin/Projects/FlaskMegaTutorial/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/oddmin/Projects/FlaskMegaTutorial/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/oddmin/Projects/FlaskMegaTutorial/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/oddmin/Projects/FlaskMegaTutorial/app/routes.py", line 89, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/oddmin/Projects/FlaskMegaTutorial/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/oddmin/Projects/FlaskMegaTutorial/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/oddmin/Projects/FlaskMegaTutorial/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/oddmin/Projects/FlaskMegaTutorial/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/oddmin/Projects/FlaskMegaTutorial/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/oddmin/Projects/FlaskMegaTutorial/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/oddmin/Projects/FlaskMegaTutorial/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/oddmin/Projects/FlaskMegaTutorial/app/templates/base.html", line 1, in top-level template code
    {% extends 'boostrap/base.html' %}
  File "/home/oddmin/Projects/FlaskMegaTutorial/venv/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/oddmin/Projects/FlaskMegaTutorial/venv/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: boostrap/base.html
2019-10-08 14:29:01,455 INFO: Microblog startup [in /home/oddmin/Projects/FlaskMegaTutorial/app/__init__.py:51]
